import type { LessonPhrase, LessonTopic, VocabularyGroup } from './aula1Data';

// Curadoria da transcrição: exemplos didáticos normalizados; sem conversas pessoais.
export const AULA6_KEY_PHRASES: LessonPhrase[] = [
  { id: 'a6-chair-whose', hanzi: '这把椅子是谁的？', spokenPinyin: 'zhè bá yǐzi | shì shéi de?', translation: 'De quem é esta cadeira?' },
  { id: 'a6-chair-mine', hanzi: '这把椅子是我的。', spokenPinyin: 'zhè bá yǐzi | shì wǒ de.', translation: 'Esta cadeira é minha.' },
  { id: 'a6-cat-sleep', hanzi: '小猫在椅子上睡觉。', spokenPinyin: 'xiǎomāo | zài yǐzi shang shuìjiào.', translation: 'O gatinho está dormindo em cima da cadeira.', note: '上 pode ficar neutro nesta expressão de posição, como a professora destacou. A leitura plena shàng também ocorre.' },
  { id: 'a6-table-what', hanzi: '桌子上有什么？', spokenPinyin: 'zhuōzi shang | yǒu shénme?', translation: 'O que há sobre a mesa?' },
  { id: 'a6-table-milk', hanzi: '桌子上有牛奶。', spokenPinyin: 'zhuōzi shang | yǒu niúnǎi.', translation: 'Há leite sobre a mesa.' },
  { id: 'a6-pen-where', hanzi: '你的笔在哪里？', spokenPinyin: 'nǐ de bǐ | zài nǎli?', translation: 'Onde está a sua caneta?' },
  { id: 'a6-pen-table', hanzi: '我的笔在桌子上。', spokenPinyin: 'wǒ de bǐ | zài zhuōzi shang.', translation: 'Minha caneta está sobre a mesa.' },
  { id: 'a6-books-how-many', hanzi: '你买了几本书？', spokenPinyin: 'ní mǎi le | jí běn shū?', translation: 'Quantos livros você comprou?' },
  { id: 'a6-books-two', hanzi: '我买了两本书。', spokenPinyin: 'wó mǎi le | liáng běn shū.', translation: 'Eu comprei dois livros.' },
  { id: 'a6-this-book-like', hanzi: '我喜欢这本书。', spokenPinyin: 'wó xǐhuan | zhè běn shū.', translation: 'Eu gosto deste livro.' },
  { id: 'a6-two-books-like', hanzi: '我喜欢这两本书。', spokenPinyin: 'wó xǐhuan | zhè liáng běn shū.', translation: 'Eu gosto destes dois livros.' },
  { id: 'a6-chinese-books', hanzi: '你有几本中文书？', spokenPinyin: 'ní yǒu | jí běn Zhōngwén shū?', translation: 'Quantos livros de chinês você tem?', note: 'Pergunta normalizada: a transcrição repete 书 e omite palavras em algumas tentativas.' },
  { id: 'a6-person-who', hanzi: '那个人是谁？', spokenPinyin: 'nà ge rén | shì shéi?', translation: 'Quem é aquela pessoa?' },
  { id: 'a6-my-teacher', hanzi: '那是我的老师。', spokenPinyin: 'nà shì | wǒ de lǎoshī.', translation: 'Aquele é meu professor.' },
  { id: 'a6-chair-chinese-book', hanzi: '椅子上有一本中文书。', spokenPinyin: 'yǐzi shang | yǒu yì běn Zhōngwén shū.', translation: 'Há um livro de chinês sobre a cadeira.' },
  { id: 'a6-book-whose', hanzi: '那是谁的书？', spokenPinyin: 'nà shì | shéi de shū?', translation: 'De quem é aquele livro?' },
  { id: 'a6-book-mine', hanzi: '是我的书，谢谢。', spokenPinyin: 'shì wǒ de shū, | xièxie.', translation: 'É meu livro, obrigado.' },
  { id: 'a6-second-book', hanzi: '这是我的第二本中文书。', spokenPinyin: 'zhè shì wǒ de | dì èr běn Zhōngwén shū.', translation: 'Este é meu segundo livro de chinês.' },
  { id: 'a6-tomorrow-morning', hanzi: '不客气。你明天上午在哪儿？', spokenPinyin: 'bú kèqi. | nǐ míngtiān shàngwǔ | zài nǎr?', translation: 'De nada. Onde você estará amanhã de manhã?' },
  { id: 'a6-school-study', hanzi: '我明天上午在学校学习。', spokenPinyin: 'wǒ míngtiān shàngwǔ | zài xuéxiào xuéxí.', translation: 'Amanhã de manhã eu vou estudar na escola.' },
  { id: 'a6-first-china', hanzi: '我第一次来中国。', spokenPinyin: 'wǒ dì yī cì | lái Zhōngguó.', translation: 'É a primeira vez que venho à China.', note: 'Em 第一, 一 permanece yī: não aplique a mudança usada em uma quantidade.' },
  { id: 'a6-second-time', hanzi: '这是我第二次来这里。', spokenPinyin: 'zhè shì wǒ dì èr cì | lái zhèli.', translation: 'Esta é a segunda vez que venho aqui.' },
  { id: 'a6-two-times', hanzi: '我已经来了两次了。', spokenPinyin: 'wó yǐjīng | lái le liǎng cì le.', translation: 'Eu já vim duas vezes.' },
  { id: 'a6-learn-cook', hanzi: '他在家里学习做中国菜。', spokenPinyin: 'tā zài jiāli | xuéxí zuò Zhōngguó cài.', translation: 'Ele está aprendendo a preparar comida chinesa em casa.', note: '学习做 é aprender a fazer, não duas ações independentes: estudar e cozinhar.' },
  { id: 'a6-learning-what', hanzi: '你在学习什么？', spokenPinyin: 'nǐ zài xuéxí shénme?', translation: 'O que você está aprendendo?' },
  { id: 'a6-learning-chinese', hanzi: '我在学习中文。', spokenPinyin: 'wǒ zài xuéxí Zhōngwén.', translation: 'Estou estudando chinês.' },
  { id: 'a6-learning-sing', hanzi: '我在学习唱歌。', spokenPinyin: 'wǒ zài xuéxí chànggē.', translation: 'Estou aprendendo a cantar.' },
  { id: 'a6-day-class-q', hanzi: '你白天有课吗？', spokenPinyin: 'nǐ báitiān | yǒu kè ma?', translation: 'Você tem aula durante o dia?' },
  { id: 'a6-day-two-classes', hanzi: '我白天有两节课。', spokenPinyin: 'wǒ báitiān | yǒu liǎng jié kè.', translation: 'Tenho duas aulas durante o dia.' },
  { id: 'a6-day-school', hanzi: '他们白天去学校。', spokenPinyin: 'tāmen báitiān | qù xuéxiào.', translation: 'Eles vão à escola durante o dia.' },
  { id: 'a6-like-read', hanzi: '你喜欢读书吗？', spokenPinyin: 'ní xǐhuan dúshū ma?', translation: 'Você gosta de ler?' },
  { id: 'a6-read-every-day', hanzi: '我每天都读书。', spokenPinyin: 'wǒ | měitiān dōu dúshū.', translation: 'Eu leio livros todos os dias.' },
  { id: 'a6-her-dog', hanzi: '她和小狗在外面。', spokenPinyin: 'tā hé xiáogǒu | zài wàimian.', translation: 'Ela e o cachorrinho estão lá fora.' },
  { id: 'a6-eat-with-who', hanzi: '你和谁去吃饭？', spokenPinyin: 'nǐ hé shéi | qù chīfàn?', translation: 'Com quem você vai comer?' },
  { id: 'a6-eat-with-friends', hanzi: '我和朋友去吃饭。', spokenPinyin: 'wǒ hé péngyou | qù chīfàn.', translation: 'Vou comer com meus amigos.' },
  { id: 'a6-her-who', hanzi: '她是谁？', spokenPinyin: 'tā shì shéi?', translation: 'Quem é ela?' },
  { id: 'a6-my-friend', hanzi: '她是我的朋友。', spokenPinyin: 'tā shì | wǒ de péngyou.', translation: 'Ela é minha amiga.' },
  { id: 'a6-can-sing-q', hanzi: '你会唱歌吗？', spokenPinyin: 'nǐ huì chànggē ma?', translation: 'Você sabe cantar?' },
  { id: 'a6-can-sing', hanzi: '我会唱歌。', spokenPinyin: 'wǒ huì chànggē.', translation: 'Eu sei cantar.' },
  { id: 'a6-song-opinion', hanzi: '你觉得这首歌怎么样？', spokenPinyin: 'nǐ juéde | zhè shǒu gē zěnmeyàng?', translation: 'O que você acha desta música?' },
  { id: 'a6-song-nice', hanzi: '非常好听。', spokenPinyin: 'fēicháng hǎotīng.', translation: 'É muito agradável de ouvir.' },
  { id: 'a6-sing-well', hanzi: '你唱歌很好听。', spokenPinyin: 'nǐ chànggē | hén hǎotīng.', translation: 'Você canta muito bem.' },
  { id: 'a6-evening-tv-q', hanzi: '你晚上看电视吗？', spokenPinyin: 'nǐ wǎnshang | kàn diànshì ma?', translation: 'Você assiste à televisão à noite?' },
  { id: 'a6-half-hour-tv', hanzi: '我看半个小时。', spokenPinyin: 'wǒ kàn | bàn ge xiǎoshí.', translation: 'Eu assisto por meia hora (duração, não horário).', note: '小时 é 3º + 2º tom. Não aplique a regra de dois terceiros tons aqui.' },
  { id: 'a6-like-animal-q', hanzi: '你喜欢什么动物？', spokenPinyin: 'ní xǐhuan shénme dòngwù?', translation: 'De que animal você gosta?' },
  { id: 'a6-like-dog', hanzi: '我喜欢小狗。', spokenPinyin: 'wó xǐhuan | xiáogǒu.', translation: 'Eu gosto de cachorrinhos.' },
  { id: 'a6-play-outside', hanzi: '我在外面玩。', spokenPinyin: 'wǒ zài wàimian wán.', translation: 'Eu brinco lá fora.' },
  { id: 'a6-blocks', hanzi: '妈妈和我玩积木。', spokenPinyin: 'māma hé wǒ | wán jīmù.', translation: 'Minha mãe e eu brincamos com blocos de montar.' },
  { id: 'a6-saturday-q', hanzi: '明天星期六，你做什么？', spokenPinyin: 'míngtiān xīngqīliù, | nǐ zuò shénme?', translation: 'Amanhã é sábado. O que você vai fazer?' },
  { id: 'a6-saturday-plan', hanzi: '我白天在家里读书，晚上和朋友们去外边唱歌。', spokenPinyin: 'wǒ báitiān zài jiāli dúshū, | wǎnshang hé péngyoumen | qù wàibian chànggē.', translation: 'Durante o dia leio em casa; à noite saio para cantar com meus amigos.' },
  { id: 'a6-saturday-polite-q', hanzi: '您星期六做什么？', spokenPinyin: 'nín xīngqīliù | zuò shénme?', translation: 'O que o senhor ou a senhora faz no sábado?' },
  { id: 'a6-home-activities', hanzi: '我在家里做饭、看电视，和孩子们、小狗玩。', spokenPinyin: 'wǒ zài jiāli | zuòfàn, kàn diànshì, | hé háizimen, xiáogǒu wán.', translation: 'Em casa cozinho, assisto à televisão e brinco com as crianças e o cachorrinho.' },
  { id: 'a6-also-dog', hanzi: '我也有一只小狗。', spokenPinyin: 'wǒ | yé yǒu yì zhī xiáogǒu.', translation: 'Eu também tenho um cachorrinho.', note: 'Blocos para treinar: 我 | 也有 | 一只 | 小狗. 也有 e 小狗 passam de 3–3 para 2–3.' },
  { id: 'a6-cannot-see', hanzi: '我看不到。', spokenPinyin: 'wǒ kàn bu dào.', translation: 'Eu não consigo ver.', note: '不 fica leve no complemento potencial 看不到. 不看 significa não olhar/assistir, não incapacidade de ver.' },
  { id: 'a6-now-see', hanzi: '现在能看见了。', spokenPinyin: 'xiànzài néng kànjiàn le.', translation: 'Agora consigo ver.' },
  { id: 'a6-table-books-cups', hanzi: '桌子上有书和杯子。', spokenPinyin: 'zhuōzi shang | yǒu shū hé bēizi.', translation: 'Há livros e copos sobre a mesa.' },
  { id: 'a6-children-tv', hanzi: '孩子们都在家里看电视。', spokenPinyin: 'háizimen dōu zài jiāli | kàn diànshì.', translation: 'As crianças estão todas em casa assistindo à televisão.' },
  { id: 'a6-sunday-q', hanzi: '你星期天做什么？', spokenPinyin: 'nǐ xīngqītiān | zuò shénme?', translation: 'O que você faz no domingo?' },
  { id: 'a6-sunday-plan', hanzi: '我星期天白天做饭，晚上上课。', spokenPinyin: 'wǒ xīngqītiān báitiān zuòfàn, | wǎnshang shàngkè.', translation: 'No domingo cozinho durante o dia e tenho aula à noite.' },
  { id: 'a6-cinema-meet', hanzi: '我们在电影院外边见吧。', spokenPinyin: 'wǒmen zài diànyǐngyuàn wàibian | jiàn ba.', translation: 'Vamos nos encontrar do lado de fora do cinema.' },
  { id: 'a6-tongue-twister', hanzi: '十是十，十四是十四，四十是四十。十四不是四十，四十不是十四。', spokenPinyin: 'shí shì shí, | shísì shì shísì, | sìshí shì sìshí. | shísì bú shì sìshí, | sìshí bú shì shísì.', translation: 'Dez é dez, quatorze é quatorze, quarenta é quarenta. Quatorze não é quarenta e quarenta não é quatorze.', note: 'Treino extra de s/sh e dos tons de 四 (4º) e 十 (2º).' },
];

const phrase = (id: string): LessonPhrase => AULA6_KEY_PHRASES.find(item => item.id === `a6-${id}`)!;
export const AULA6_LESSON_TOPICS: LessonTopic[] = [
  { marker: '上', title: 'Objeto antes da posição', summary: '在 + objeto de referência + 上 indica onde alguém ou algo está.', points: ['Use 在椅子上, não 在上椅子.', 'Sujeito + lugar + ação: 小猫在椅子上睡觉.', '上楼 é subir de andar: um uso verbal diferente do 上 de posição.'], examples: [phrase('cat-sleep'), phrase('pen-table')] },
  { marker: '本', title: 'Classificadores: livros e outros objetos', summary: 'O classificador acompanha o número ou demonstrativo e vem antes do substantivo.', points: ['Livros: 一本书、两本书、这本书.', 'Cadeiras: 一把椅子; animais pequenos: 一只小狗.', 'Também apareceram 一瓶水、一个苹果、一台电脑、一件衣服 e 一首歌.'], examples: [phrase('books-how-many'), phrase('books-two'), phrase('two-books-like')] },
  { marker: '的', title: 'De quem é? Quem é?', summary: '谁 pergunta quem; 谁的 pergunta de quem é algo.', points: ['那个人是谁? identifica uma pessoa.', '那是谁的书? pergunta o dono do livro.', '是我的书 ou 这本书是我的: as duas formas expressam posse.'], examples: [phrase('person-who'), phrase('book-whose'), phrase('book-mine')] },
  { marker: '第', title: 'Quantidade não é ordem', summary: '第 + número (+ classificador + substantivo) indica a posição numa sequência.', points: ['两本书 = dois livros; 第二本书 = o segundo livro.', '两次 = duas vezes no total; 第二次 = a segunda ocasião.', '第一 mantém 一 como yī; 第二 usa 二, não 两.'], examples: [phrase('second-book'), phrase('first-china'), phrase('second-time'), phrase('two-times')] },
  { marker: '学', title: 'Aprender uma atividade', summary: '学习 pode ser seguido pelo que se aprende: um idioma ou uma habilidade.', points: ['学习中文 = estudar chinês.', '学习做中国菜 = aprender a preparar comida chinesa.', 'Pratique também 学习唱歌、跳舞、画画 e 游泳.'], examples: [phrase('learn-cook'), phrase('learning-what'), phrase('learning-sing')] },
  { marker: '和', title: 'Com quem? E quem?', summary: '和 liga pessoas ou substantivos; também introduz companhia antes da ação.', points: ['我和朋友: eu e meus amigos / com meus amigos, conforme a frase.', '你和谁去吃饭? pergunta a companhia.', 'Não use 和 como ligação automática entre quaisquer dois verbos.'], examples: [phrase('her-dog'), phrase('eat-with-who'), phrase('eat-with-friends')] },
  { marker: '时', title: 'Dia, noite, hábito e duração', summary: 'O tempo vem antes da ação; a duração pode aparecer depois do verbo.', points: ['白天 = durante o dia; 晚上 = à noite.', '每天都读书 = ler todos os dias.', '我看半个小时 = assistir por meia hora.'], examples: [phrase('day-two-classes'), phrase('read-every-day'), phrase('half-hour-tv'), phrase('saturday-plan')] },
  { marker: '做', title: 'Ações e opiniões do fim de semana', summary: '做 significa fazer; 坐 significa sentar. Eles têm a mesma pronúncia, mas não o mesmo uso.', points: ['做饭、做作业、做手工: cozinhar, fazer a lição, fazer artesanato.', '玩游戏、玩积木: jogar, brincar com blocos.', '觉得…怎么样? pede opinião; 好听 descreve algo agradável de ouvir.', '看不到 / 看不见 = não conseguir ver; 不看 = não olhar/assistir.'], examples: [phrase('song-opinion'), phrase('sing-well'), phrase('home-activities'), phrase('cannot-see')] },
];

export const AULA6_VOCABULARY_GROUPS: VocabularyGroup[] = [
  { title: 'Livros, posse e classificadores', description: 'Diferencie quantidade, ordem e dono do objeto.', words: [
    { hanzi: '书', translation: 'livro' }, { hanzi: '中文书', translation: 'livro de chinês' }, { hanzi: '本', translation: 'classificador de livros' }, { hanzi: '把', translation: 'classificador de cadeiras' }, { hanzi: '只', translation: 'classificador de animais', note: 'Aqui se lê zhī, 1º tom.' }, { hanzi: '瓶', translation: 'garrafa' }, { hanzi: '台', translation: 'classificador de aparelhos' }, { hanzi: '件', translation: 'classificador de roupas' }, { hanzi: '首', translation: 'classificador de músicas' }, { hanzi: '谁', translation: 'quem' }, { hanzi: '谁的', translation: 'de quem' }, { hanzi: '那', translation: 'aquele' }, { hanzi: '第', translation: 'prefixo de ordem' }, { hanzi: '第一', translation: 'primeiro' }, { hanzi: '第二', translation: 'segundo' }, { hanzi: '次', translation: 'vez' },
  ] },
  { title: 'Casa e posições', description: 'Objetos usados como referência e exemplos de existência.', words: [
    { hanzi: '椅子', translation: 'cadeira' }, { hanzi: '桌子', translation: 'mesa' }, { hanzi: '笔', translation: 'caneta' }, { hanzi: '杯子', translation: 'copo' }, { hanzi: '电脑', translation: 'computador' }, { hanzi: '上', translation: 'em cima', note: 'Leitura plena shàng; pode ser leve/neutra depois do objeto de referência.' }, { hanzi: '外边', translation: 'lado de fora' }, { hanzi: '小狗', translation: 'cachorrinho' }, { hanzi: '积木', translation: 'blocos de montar' }, { hanzi: '电视', translation: 'televisão' },
  ] },
  { title: 'Atividades e companhia', description: 'Verbos e combinações para falar da sua rotina.', words: [
    { hanzi: '学习', translation: 'estudar / aprender' }, { hanzi: '读书', translation: 'ler livros' }, { hanzi: '做', translation: 'fazer' }, { hanzi: '坐', translation: 'sentar' }, { hanzi: '做饭', translation: 'cozinhar' }, { hanzi: '唱歌', translation: 'cantar' }, { hanzi: '歌', translation: 'música' }, { hanzi: '跳舞', translation: 'dançar' }, { hanzi: '画画', translation: 'desenhar' }, { hanzi: '游泳', translation: 'nadar' }, { hanzi: '玩', translation: 'brincar' }, { hanzi: '玩游戏', translation: 'jogar' }, { hanzi: '看电视', translation: 'assistir à televisão' }, { hanzi: '睡觉', translation: 'dormir' }, { hanzi: '朋友', translation: 'amigo' }, { hanzi: '和', translation: 'e / com' }, { hanzi: '觉得', translation: 'achar / considerar' }, { hanzi: '怎么样', translation: 'como é' }, { hanzi: '好听', translation: 'agradável de ouvir' }, { hanzi: '看不到', translation: 'não conseguir ver' },
  ] },
  { title: 'Tempo e frequência', description: 'Quando, por quanto tempo e com que frequência.', words: [
    { hanzi: '白天', translation: 'durante o dia' }, { hanzi: '晚上', translation: 'à noite' }, { hanzi: '上午', translation: 'de manhã' }, { hanzi: '每天', translation: 'todos os dias' }, { hanzi: '都', translation: 'todos / sempre', note: '每天都 reforça a regularidade; 孩子们都 indica todas as crianças.' }, { hanzi: '星期六', translation: 'sábado' }, { hanzi: '星期天', translation: 'domingo' }, { hanzi: '半个小时', translation: 'meia hora' }, { hanzi: '两节课', translation: 'duas aulas' },
  ] },
];

export const AULA6_NUMBER_ROWS = [
  { hanzi: '一本书', translation: 'um livro — quantidade' }, { hanzi: '两本书', translation: 'dois livros — quantidade' },
  { hanzi: '第一本书', translation: 'o primeiro livro — ordem' }, { hanzi: '第二本书', translation: 'o segundo livro — ordem' },
  { hanzi: '第一次', translation: 'a primeira vez' }, { hanzi: '第二次', translation: 'a segunda vez' }, { hanzi: '两次', translation: 'duas vezes no total' },
  { hanzi: '一把椅子', translation: 'uma cadeira' }, { hanzi: '一只小狗', translation: 'um cachorrinho' }, { hanzi: '一首歌', translation: 'uma música' },
  { hanzi: '两节课', translation: 'duas aulas' }, { hanzi: '半个小时', translation: 'meia hora' }, { hanzi: '十四', translation: 'quatorze' }, { hanzi: '四十', translation: 'quarenta' },
];
export const AULA6_PINYIN_NOTES = [
  { title: '谁 — shéi / 哪儿 — nǎr', detail: '谁 tem 2º tom; 哪儿 tem 3º. Não transforme o 2º tom de 谁 em uma curva de 3º tom.' },
  { title: '也有 — yé yǒu / 小狗 — xiáogǒu', detail: 'Dentro desses blocos de dois terceiros tons, o primeiro passa a 2º. Em 我也有一只小狗, pratique 我 | 也有 | 一只 | 小狗, sem aplicar uma sequência mecânica à frase toda.' },
  { title: '两本 — liáng běn / 几本 — jí běn', detail: 'Também são blocos 3–3 que soam 2–3. Os caracteres continuam escritos da mesma maneira.' },
  { title: '第一 — dì yī / 一本 — yì běn', detail: 'Em ordinais, 一 conserva o 1º tom. Na quantidade 一本, muda para 4º antes de 本. Não confunda primeira posição com quantidade de um.' },
  { title: '上 — shàng / shang', detail: 'Depois de um objeto de referência, 上 pode ser leve/neutro, como a professora praticou em 椅子上. A leitura plena também é possível: não é uma regra de neutralização para todo uso de 上.' },
  { title: '做 / 坐 — zuò', detail: 'O som é o mesmo: 4º tom. Escolha o caractere pelo sentido: fazer ou sentar.' },
  { title: '白天 — báitiān / 读书 — dúshū', detail: 'As duas palavras começam com 2º tom crescente e terminam em 1º tom alto.' },
  { title: '小时 — xiǎoshí / 很好听 — hén hǎotīng', detail: '时 é 2º tom, portanto 小 conserva o 3º em 小时; em 很好听, 很 sobe antes do 3º tom de 好.' },
  { title: '玩儿 — wánr', detail: 'Na fala coloquial pode haver 儿化: o final se liga à sílaba, não é uma sílaba independente.' },
  { title: '四 / 十 — sì / shí', detail: 'Treine a diferença entre s e sh, além de 4º e 2º tom, usando 十四 e 四十 e o trava-língua da aula.' },
];
export const AULA6_HANZI_CORRECTIONS = [
  { hanzi: '做 / 坐', title: 'Fazer não é sentar', detail: '做 tem 亻 à esquerda; 坐 tem duas pessoas sobre 土. A transcrição confunde os dois, mas 做饭 e 做手工 usam 做.' },
  { hanzi: '第 / 弟', title: 'Ordem e irmão mais novo', detail: '第 tem o radical de bambu ⺮ em cima e forma 第一、第二. 弟 aparece em 弟弟.' },
  { hanzi: '和 / 河', title: 'E/com não é rio', detail: '和 combina 禾 e 口. 河 tem o radical de água 氵 e significa rio. Para “eu e amigos”, use 和.' },
  { hanzi: '那 / 哪', title: 'Aquele e qual/onde', detail: '哪 acrescenta 口 à esquerda de 那. 那个人 é aquela pessoa; 哪儿 pergunta onde.' },
  { hanzi: '本 / 木', title: 'Livros: 本', detail: '本 é 木 com um traço horizontal curto perto da base. Não omita esse traço.' },
  { hanzi: '外', title: 'Lado de fora', detail: 'Use 外 em 外边. A transcrição contém palavras trocadas em alguns treinos; não as copie como vocabulário.' },
  { hanzi: '唱', title: 'Cantar', detail: '口 fica à esquerda e 昌 à direita. Preserve os retângulos de 口 e 日 sem prolongar traços além da moldura.' },
  { hanzi: '书 / 读', title: 'Livro e ler', detail: '书 é livro; 读 é ler e começa pelo radical simplificado de fala 讠. A combinação é 读书.' },
];

export const AULA6_WRITING_EXERCISES = [
  { id: 'a6-w-chair', prompt: 'De quem é esta cadeira?', answer: '这把椅子是谁的？', hint: 'Use o classificador do objeto e uma pergunta de posse.' },
  { id: 'a6-w-sleep', prompt: 'O gatinho está dormindo em cima da cadeira.', answer: '小猫在椅子上睡觉。', hint: 'Coloque a referência antes da posição; a ação vem por último.' },
  { id: 'a6-w-books-q', prompt: 'Quantos livros você comprou?', answer: '你买了几本书？', hint: 'Pergunte a quantidade com o classificador de livros.' },
  { id: 'a6-w-books', prompt: 'Eu comprei dois livros.', answer: '我买了两本书。', hint: 'Use quantidade, não um ordinal.' },
  { id: 'a6-w-whose', prompt: 'De quem é aquele livro?', answer: '那是谁的书？', hint: 'Não pergunte apenas quem é a pessoa; pergunte a quem pertence o objeto.' },
  { id: 'a6-w-second', prompt: 'Este é meu segundo livro de chinês.', answer: '这是我的第二本中文书。', hint: 'Indique a ordem antes do classificador.' },
  { id: 'a6-w-first', prompt: 'É a primeira vez que venho à China.', answer: '我第一次来中国。', hint: 'Indique a primeira ocasião antes do verbo de movimento.' },
  { id: 'a6-w-study', prompt: 'Amanhã de manhã eu vou estudar na escola.', answer: '我明天上午在学校学习。', hint: 'Siga a ordem pessoa, tempo, lugar e atividade.' },
  { id: 'a6-w-learn', prompt: 'Ele aprende a preparar comida chinesa em casa.', answer: '他在家里学习做中国菜。', hint: 'Depois de aprender, diga qual atividade está aprendendo.' },
  { id: 'a6-w-day', prompt: 'Tenho duas aulas durante o dia.', answer: '我白天有两节课。', hint: 'Use o classificador de aulas, não o de livros.' },
  { id: 'a6-w-daily', prompt: 'Eu leio todos os dias.', answer: '我每天都读书。', hint: 'Indique frequência antes da ação.' },
  { id: 'a6-w-company', prompt: 'Com quem você vai comer?', answer: '你和谁去吃饭？', hint: 'A companhia aparece antes do verbo de movimento.' },
  { id: 'a6-w-song', prompt: 'O que você acha desta música?', answer: '你觉得这首歌怎么样？', hint: 'Use uma expressão de opinião e o classificador de músicas.' },
  { id: 'a6-w-tv', prompt: 'Você assiste à televisão à noite?', answer: '你晚上看电视吗？', hint: 'O período do dia vem antes da ação.' },
  { id: 'a6-w-half', prompt: 'Eu assisto por meia hora.', answer: '我看半个小时。', hint: 'A duração fica depois do verbo.' },
  { id: 'a6-w-dog', prompt: 'Eu também tenho um cachorrinho.', answer: '我也有一只小狗。', hint: 'Indique também, existência e o classificador do animal.' },
  { id: 'a6-w-see', prompt: 'Eu não consigo ver.', answer: '我看不到。', hint: 'Expresse impossibilidade de perceber, não decisão de não olhar.' },
  { id: 'a6-w-meet', prompt: 'Vamos nos encontrar do lado de fora do cinema.', answer: '我们在电影院外边见吧。', hint: 'Lugar antes do encontro; termine com uma sugestão.' },
];

export const AULA6_LISTENING_EXERCISES = [
  { phraseId: 'a6-chair-whose', choices: ['De quem é esta cadeira?', 'Onde está esta cadeira?', 'Quem está sentado na cadeira?'] },
  { phraseId: 'a6-cat-sleep', choices: ['O gatinho está dormindo em cima da cadeira.', 'O gatinho está dormindo debaixo da cadeira.', 'O cachorro sobe na cadeira.'] },
  { phraseId: 'a6-books-two', choices: ['Eu comprei dois livros.', 'Eu comprei o segundo livro.', 'Eu li dois livros.'] },
  { phraseId: 'a6-second-book', choices: ['Este é meu segundo livro de chinês.', 'Eu tenho dois livros de chinês.', 'Este é o segundo livro do professor.'] },
  { phraseId: 'a6-first-china', choices: ['É a primeira vez que venho à China.', 'Eu já vim duas vezes à China.', 'Vou à China com a primeira pessoa.'] },
  { phraseId: 'a6-two-times', choices: ['Eu já vim duas vezes.', 'Esta é a minha primeira visita.', 'Quero vir duas vezes.'] },
  { phraseId: 'a6-learn-cook', choices: ['Ele aprende a preparar comida chinesa em casa.', 'Ele ensina chinês na cozinha.', 'Ele aprende a preparar comida chinesa na escola.'] },
  { phraseId: 'a6-day-two-classes', choices: ['Tenho duas aulas durante o dia.', 'Tenho duas aulas à noite.', 'Esta é minha segunda aula.'] },
  { phraseId: 'a6-read-every-day', choices: ['Eu leio todos os dias.', 'Eu leio apenas durante o dia.', 'Todos os amigos estão lendo.'] },
  { phraseId: 'a6-eat-with-who', choices: ['Com quem você vai comer?', 'Onde você vai comer?', 'O que você quer comer?'] },
  { phraseId: 'a6-song-opinion', choices: ['O que você acha desta música?', 'Você sabe cantar esta música?', 'De quem é esta música?'] },
  { phraseId: 'a6-half-hour-tv', choices: ['Eu assisto por meia hora.', 'Eu assisto às duas e meia.', 'Eu assisto por uma hora e meia.'] },
  { phraseId: 'a6-also-dog', choices: ['Eu também tenho um cachorrinho.', 'Eu só tenho um cachorrinho.', 'Eu também gosto do seu cachorrinho.'] },
  { phraseId: 'a6-cannot-see', choices: ['Eu não consigo ver.', 'Eu não quero olhar.', 'Eu não olhei ontem.'] },
  { phraseId: 'a6-children-tv', choices: ['As crianças estão todas em casa assistindo à televisão.', 'As crianças assistem à televisão na escola.', 'As crianças estão todas em casa lendo.'] },
  { phraseId: 'a6-cinema-meet', choices: ['Vamos nos encontrar do lado de fora do cinema.', 'Vamos nos encontrar dentro do cinema.', 'Vamos nos encontrar de manhã na livraria.'] },
];
export const AULA6_HOMEWORK = [
  'Prática sugerida com base na aula: repita o diálogo do livro na cadeira, trocando o objeto e seu dono.',
  'Monte pares com quantidade e ordem: dois livros / segundo livro; duas vezes / segunda vez.',
  'Responda o que está aprendendo, usando um idioma e três atividades: cantar, dançar, desenhar ou nadar.',
  'Conte seus planos de sábado: uma atividade durante o dia e outra à noite, dizendo com quem vai.',
  'Leia e grave 也有, 小狗, 两本 e 很好听; compare as mudanças de 3º tom com os blocos indicados.',
  'Escreva os caracteres da aula e compare os pares 做/坐, 第/弟, 和/河 e 那/哪.',
  'Treine o trava-língua de 十四 e 四十 devagar antes de acelerar.',
  'Os exercícios acima são propostas do site. A transcrição menciona o envio de deveres depois, mas não contém uma lista final completa da professora.',
];
