import type { LessonPhrase, LessonTopic, VocabularyGroup } from './aula1Data';

export const AULA5_KEY_PHRASES: LessonPhrase[] = [
  { id: 'a5-room', hanzi: '这是我的房间。', spokenPinyin: 'zhè shì | wǒ de fángjiān.', translation: 'Este é o meu quarto.' },
  { id: 'a5-outside-person-q', hanzi: '门外有人吗？', spokenPinyin: 'mén wài | yǒu rén ma?', translation: 'Tem alguém do lado de fora da porta?' },
  { id: 'a5-outside-no-person', hanzi: '门外没有人。', spokenPinyin: 'mén wài | méiyǒu rén.', translation: 'Não há ninguém do lado de fora da porta.' },
  { id: 'a5-dog-outside', hanzi: '房间外有一只小狗。', spokenPinyin: 'fángjiān wài | yǒu yì zhī xiǎogǒu.', translation: 'Há um cachorrinho fora do quarto.' },
  { id: 'a5-cat-outside', hanzi: '房间外有一只小猫。', spokenPinyin: 'fángjiān wài | yǒu yì zhī xiǎomāo.', translation: 'Há um gatinho fora do quarto.' },
  { id: 'a5-like-cats-q', hanzi: '你喜欢猫吗？', spokenPinyin: 'nǐ xǐhuan māo ma?', translation: 'Você gosta de gatos?' },
  { id: 'a5-like-cats', hanzi: '我很喜欢猫。', spokenPinyin: 'wǒ hěn xǐhuan māo.', translation: 'Eu gosto muito de gatos.' },
  { id: 'a5-see-bird-q', hanzi: '你看见那只鸟了吗？', spokenPinyin: 'nǐ kànjiàn | nà zhī niǎo le ma?', translation: 'Você viu aquele pássaro?' },
  { id: 'a5-see-it', hanzi: '我看见了。', spokenPinyin: 'wǒ kànjiàn le.', translation: 'Eu vi.' },
  { id: 'a5-baozi-table', hanzi: '我看见桌子上有包子。', spokenPinyin: 'wǒ kànjiàn | zhuōzi shàng yǒu bāozi.', translation: 'Eu vejo pãezinhos sobre a mesa.' },
  { id: 'a5-cat-where', hanzi: '小猫在哪里？', spokenPinyin: 'xiǎomāo | zài nǎli?', translation: 'Onde está o gatinho?' },
  { id: 'a5-cat-sofa-on', hanzi: '小猫在沙发上面。', spokenPinyin: 'xiǎomāo | zài shāfā shàngmian.', translation: 'O gatinho está em cima do sofá.' },
  { id: 'a5-cat-table-under', hanzi: '小猫在桌子下面。', spokenPinyin: 'xiǎomāo | zài zhuōzi xiàmian.', translation: 'O gatinho está debaixo da mesa.' },
  { id: 'a5-cat-sofa-left', hanzi: '小猫在沙发左边。', spokenPinyin: 'xiǎomāo | zài shāfā zuǒbian.', translation: 'O gatinho está à esquerda do sofá.' },
  { id: 'a5-cat-sofa-right', hanzi: '小猫在沙发右边。', spokenPinyin: 'xiǎomāo | zài shāfā yòubian.', translation: 'O gatinho está à direita do sofá.' },
  { id: 'a5-santa-where', hanzi: '圣诞老人在哪里？', spokenPinyin: 'Shèngdàn Lǎorén | zài nǎli?', translation: 'Onde está o Papai Noel?' },
  { id: 'a5-santa-behind', hanzi: '圣诞老人在椅子后面。', spokenPinyin: 'Shèngdàn Lǎorén | zài yǐzi hòumian.', translation: 'O Papai Noel está atrás da cadeira.' },
  { id: 'a5-cat-bed', hanzi: '小猫在床上。', spokenPinyin: 'xiǎomāo | zài chuáng shàng.', translation: 'O gatinho está sobre a cama.' },
  { id: 'a5-cat-wardrobe', hanzi: '小猫在衣柜里。', spokenPinyin: 'xiǎomāo | zài yīguì li.', translation: 'O gatinho está dentro do guarda-roupa.' },
  { id: 'a5-cat-bookshelf', hanzi: '小猫在书架上。', spokenPinyin: 'xiǎomāo | zài shūjià shàng.', translation: 'O gatinho está sobre a estante.' },
  { id: 'a5-dog-chair', hanzi: '小狗在椅子下面。', spokenPinyin: 'xiǎogǒu | zài yǐzi xiàmian.', translation: 'O cachorrinho está debaixo da cadeira.' },
  { id: 'a5-dog-front', hanzi: '小狗在房子前面。', spokenPinyin: 'xiǎogǒu | zài fángzi qiánmian.', translation: 'O cachorrinho está na frente da casa.' },
  { id: 'a5-dog-behind', hanzi: '小狗在房子后面。', spokenPinyin: 'xiǎogǒu | zài fángzi hòumian.', translation: 'O cachorrinho está atrás da casa.' },
  { id: 'a5-dog-middle', hanzi: '小狗在两个房子中间。', spokenPinyin: 'xiǎogǒu | zài liǎng ge fángzi zhōngjiān.', translation: 'O cachorrinho está entre duas casas.' },
  { id: 'a5-pretty-today', hanzi: '你今天真漂亮。', spokenPinyin: 'nǐ jīntiān | zhēn piàoliang.', translation: 'Você está muito bonita hoje.' },
  { id: 'a5-did-not-see', hanzi: '我没看见。', spokenPinyin: 'wǒ méi kànjiàn.', translation: 'Eu não vi.' },
  { id: 'a5-it-where', hanzi: '它在哪儿呢？', spokenPinyin: 'tā zài nǎr ne?', translation: 'Onde ele está?' },
  { id: 'a5-it-under-table', hanzi: '它在桌子下呢。', spokenPinyin: 'tā zài zhuōzi xià ne.', translation: 'Ele está debaixo da mesa.' },
  { id: 'a5-cat-pretty', hanzi: '这只小猫真漂亮。', spokenPinyin: 'zhè zhī xiǎomāo | zhēn piàoliang.', translation: 'Este gatinho é muito bonito.' },
  { id: 'a5-you-where', hanzi: '你在哪儿呢？', spokenPinyin: 'nǐ zài nǎr ne?', translation: 'Onde você está?' },
  { id: 'a5-at-home', hanzi: '我在家里。', spokenPinyin: 'wǒ zài jiāli.', translation: 'Estou em casa.' },
  { id: 'a5-school-big', hanzi: '你的学校很大。', spokenPinyin: 'nǐ de xuéxiào | hěn dà.', translation: 'A sua escola é grande.' },
  { id: 'a5-many-students', hanzi: '我们学校有很多学生。', spokenPinyin: 'wǒmen xuéxiào | yǒu hěn duō xuésheng.', translation: 'Nossa escola tem muitos alunos.' },
  { id: 'a5-meet-where', hanzi: '我们在哪儿见呢？', spokenPinyin: 'wǒmen | zài nǎr jiàn ne?', translation: 'Onde vamos nos encontrar?' },
  { id: 'a5-meet-bookstore', hanzi: '我们在书店见。', spokenPinyin: 'wǒmen | zài shūdiàn jiàn.', translation: 'Vamos nos encontrar na livraria.' },
  { id: 'a5-meet-school-bookstore', hanzi: '在学校书店前见吧。', spokenPinyin: 'zài xuéxiào shūdiàn qián | jiàn ba.', translation: 'Vamos nos encontrar em frente à livraria da escola.' },
  { id: 'a5-can-arrive-two', hanzi: '下午两点你能到吗？', spokenPinyin: 'xiàwǔ liáng diǎn | nǐ néng dào ma?', translation: 'Você consegue chegar às duas da tarde?' },
  { id: 'a5-can-arrive', hanzi: '我能到。', spokenPinyin: 'wǒ néng dào.', translation: 'Eu consigo chegar.' },
  { id: 'a5-lunch-school', hanzi: '我在学校吃午饭。', spokenPinyin: 'wǒ zài xuéxiào | chī wǔfàn.', translation: 'Eu almoço na escola.' },
  { id: 'a5-can-chinese', hanzi: '你能说汉语吗？', spokenPinyin: 'nǐ néng shuō Hànyǔ ma?', translation: 'Você consegue falar chinês?' },
  { id: 'a5-speak-little', hanzi: '我能说一点。', spokenPinyin: 'wǒ néng shuō yì diǎn.', translation: 'Eu consigo falar um pouco.' },
  { id: 'a5-arrive-school-when', hanzi: '你什么时候到学校？', spokenPinyin: 'nǐ shénme shíhou | dào xuéxiào?', translation: 'Quando você chega à escola?' },
  { id: 'a5-arrive-school-two', hanzi: '我两点能到学校。', spokenPinyin: 'wǒ liáng diǎn | néng dào xuéxiào.', translation: 'Consigo chegar à escola às duas.' },
  { id: 'a5-they-where', hanzi: '他们在哪儿？', spokenPinyin: 'tāmen zài nǎr?', translation: 'Onde eles estão?' },
  { id: 'a5-chat-subway', hanzi: '他们在地铁上聊天。', spokenPinyin: 'tāmen zài dìtiě shàng | liáotiān.', translation: 'Eles estão conversando no metrô.' },
  { id: 'a5-eat-restaurant', hanzi: '他们在餐厅里吃饭。', spokenPinyin: 'tāmen zài cāntīng li | chīfàn.', translation: 'Eles estão comendo dentro do restaurante.' },
  { id: 'a5-treatment-hospital', hanzi: '他们在医院里看病。', spokenPinyin: 'tāmen zài yīyuàn li | kànbìng.', translation: 'Eles estão consultando o médico no hospital.' },
  { id: 'a5-movie-together', hanzi: '明天你能和我一起去看电影吗？', spokenPinyin: 'míngtiān | nǐ néng hé wǒ yìqǐ | qù kàn diànyǐng ma?', translation: 'Amanhã você pode ir ao cinema comigo?' },
  { id: 'a5-weekend-where', hanzi: '你周末去哪儿了？', spokenPinyin: 'nǐ zhōumò | qù nǎr le?', translation: 'Aonde você foi no fim de semana?' },
  { id: 'a5-visit-patient', hanzi: '我去医院看望病人。', spokenPinyin: 'wǒ qù yīyuàn | kànwàng bìngrén.', translation: 'Fui ao hospital visitar um paciente.' },
  { id: 'a5-doctor-q', hanzi: '你是一名医生吗？', spokenPinyin: 'nǐ shì yì míng yīshēng ma?', translation: 'Você é médico?' },
  { id: 'a5-teacher', hanzi: '不是，我是一名老师。', spokenPinyin: 'bú shì, | wǒ shì yì míng lǎoshī.', translation: 'Não, eu sou professor.' },
  { id: 'a5-brother-work', hanzi: '你哥哥在哪里工作？', spokenPinyin: 'nǐ gēge | zài nǎli gōngzuò?', translation: 'Onde seu irmão mais velho trabalha?' },
  { id: 'a5-beijing-hospital', hanzi: '他在北京的一家医院工作。', spokenPinyin: 'tā zài Běijīng de | yì jiā yīyuàn gōngzuò.', translation: 'Ele trabalha em um hospital de Pequim.' },
  { id: 'a5-job-q', hanzi: '你做什么工作？', spokenPinyin: 'nǐ zuò shénme gōngzuò?', translation: 'Qual é o seu trabalho?' },
  { id: 'a5-student', hanzi: '我是一名学生。', spokenPinyin: 'wǒ shì yì míng xuésheng.', translation: 'Eu sou estudante.' },
  { id: 'a5-hospital-busy', hanzi: '大医院病人多，医生非常忙。', spokenPinyin: 'dà yīyuàn | bìngrén duō, | yīshēng fēicháng máng.', translation: 'Hospitais grandes têm muitos pacientes e os médicos ficam muito ocupados.' },
  { id: 'a5-computer-table', hanzi: '我的电脑在桌子上。', spokenPinyin: 'wǒ de diànnǎo | zài zhuōzi shàng.', translation: 'Meu computador está sobre a mesa.' },
  { id: 'a5-meet-cinema', hanzi: '我们在电影院前见吧。', spokenPinyin: 'wǒmen | zài diànyǐngyuàn qián jiàn ba.', translation: 'Vamos nos encontrar em frente ao cinema.' },
];

export const AULA5_LESSON_TOPICS: LessonTopic[] = [
  { marker: '方', title: 'Palavras de posição', summary: '上、下、里、外、前、后、左、右 e 中间 localizam algo em relação a outro objeto.', points: ['Use 面 ou 边 em muitas posições: 上面, 下面, 左边, 右边.', '里 indica interior; 外 indica exterior.', '中间 significa no meio ou entre dois elementos.'], examples: [AULA5_KEY_PHRASES[11], AULA5_KEY_PHRASES[14], AULA5_KEY_PHRASES[23]] },
  { marker: '在', title: '在 + referência + posição', summary: 'Para dizer onde algo está, coloque 在 antes do lugar ou objeto usado como referência.', points: ['Modelo: sujeito + 在 + referência + palavra de posição.', 'A referência vem antes de 上、下、里、外 etc.', 'O verbo principal pode vir depois de toda a informação de lugar.'], examples: [AULA5_KEY_PHRASES[12], AULA5_KEY_PHRASES[18], AULA5_KEY_PHRASES[20]] },
  { marker: '有', title: 'Existência com 有 e 没有', summary: '有 apresenta o que existe em um lugar; 没有 nega essa existência.', points: ['O lugar pode abrir a frase: 门外有人吗？', 'Para animais pequenos, use o classificador 只.', 'Não use 不有; a negação correta é 没有.'], examples: [AULA5_KEY_PHRASES[1], AULA5_KEY_PHRASES[2], AULA5_KEY_PHRASES[4]] },
  { marker: '序', title: 'Lugar antes da ação', summary: 'Em chinês, a informação de lugar normalmente aparece antes da ação principal.', points: ['Modelo: sujeito + 在 + lugar + ação.', '聊天, 吃饭 e 看病 ficam no fim.', 'Essa ordem é diferente do português em muitas frases.'], examples: [AULA5_KEY_PHRASES[44], AULA5_KEY_PHRASES[45], AULA5_KEY_PHRASES[46]] },
  { marker: '能', title: '能 e 不能', summary: '能 expressa capacidade ou possibilidade pelas condições; aparece antes do verbo.', points: ['能 + verbo: 能说, 能到, 能去.', 'A negação é 不能.', 'Use 能 para combinar se alguém consegue chegar em determinado horário.'], examples: [AULA5_KEY_PHRASES[36], AULA5_KEY_PHRASES[39], AULA5_KEY_PHRASES[47]] },
  { marker: '见', title: 'Combinar lugar e horário', summary: 'Para marcar um encontro, diga tempo, lugar e depois 见; 到 indica chegada.', points: ['在哪儿见? pergunta o ponto do encontro.', '在书店见: encontrar-se na livraria.', '两点能到吗? pergunta se a pessoa consegue chegar às duas.'], examples: [AULA5_KEY_PHRASES[33], AULA5_KEY_PHRASES[34], AULA5_KEY_PHRASES[58]] },
];

export const AULA5_VOCABULARY_GROUPS: VocabularyGroup[] = [
  { title: 'Cômodos e objetos', description: 'Referências para descrever posições dentro de casa.', words: [
    { hanzi: '房间', translation: 'quarto' }, { hanzi: '书房', translation: 'escritório' }, { hanzi: '卫生间', translation: 'banheiro' }, { hanzi: '浴室', translation: 'banheiro com chuveiro' }, { hanzi: '卧室', translation: 'quarto de dormir' }, { hanzi: '客厅', translation: 'sala' }, { hanzi: '厨房', translation: 'cozinha' }, { hanzi: '门', translation: 'porta' }, { hanzi: '床', translation: 'cama' }, { hanzi: '沙发', translation: 'sofá' }, { hanzi: '椅子', translation: 'cadeira' }, { hanzi: '衣柜', translation: 'guarda-roupa' }, { hanzi: '书架', translation: 'estante' }, { hanzi: '窗户', translation: 'janela' }, { hanzi: '桌子', translation: 'mesa' },
  ] },
  { title: 'Posição e direção', description: 'Palavras que vêm depois do objeto de referência.', words: [
    { hanzi: '上面', translation: 'em cima' }, { hanzi: '下面', translation: 'embaixo' }, { hanzi: '里面', translation: 'dentro' }, { hanzi: '外面', translation: 'fora' }, { hanzi: '前面', translation: 'na frente' }, { hanzi: '后面', translation: 'atrás' }, { hanzi: '左边', translation: 'lado esquerdo' }, { hanzi: '右边', translation: 'lado direito' }, { hanzi: '中间', translation: 'no meio / entre' }, { hanzi: '旁边', translation: 'ao lado' }, { hanzi: '哪儿', translation: 'onde' }, { hanzi: '那儿', translation: 'ali' },
  ] },
  { title: 'Lugares da cidade', description: 'Locais usados com 在, 去, 到 e 见.', words: [
    { hanzi: '学校', translation: 'escola' }, { hanzi: '医院', translation: 'hospital' }, { hanzi: '超市', translation: 'supermercado' }, { hanzi: '饭店', translation: 'restaurante' }, { hanzi: '餐厅', translation: 'restaurante' }, { hanzi: '电影院', translation: 'cinema' }, { hanzi: '书店', translation: 'livraria' }, { hanzi: '地铁', translation: 'metrô' }, { hanzi: '北京', translation: 'Pequim' },
  ] },
  { title: 'Hospital e profissões', description: 'Pessoas e funções vistas na parte final da aula.', words: [
    { hanzi: '医生', translation: 'médico' }, { hanzi: '护士', translation: 'enfermeiro' }, { hanzi: '牙科医生', translation: 'dentista' }, { hanzi: '儿科医生', translation: 'pediatra' }, { hanzi: '病人', translation: 'paciente' }, { hanzi: '老师', translation: 'professor' }, { hanzi: '学生', translation: 'estudante' }, { hanzi: '司机', translation: 'motorista' }, { hanzi: '警察', translation: 'policial' }, { hanzi: '一名', translation: 'um/uma profissional' },
  ] },
  { title: 'Ações e estruturas', description: 'Verbos centrais para localizar, combinar e descrever.', words: [
    { hanzi: '在', translation: 'estar em' }, { hanzi: '有', translation: 'ter / haver' }, { hanzi: '没有', translation: 'não ter / não haver' }, { hanzi: '能', translation: 'conseguir / poder' }, { hanzi: '不能', translation: 'não conseguir' }, { hanzi: '到', translation: 'chegar' }, { hanzi: '看见', translation: 'ver' }, { hanzi: '看病', translation: 'consultar-se' }, { hanzi: '看望', translation: 'visitar' }, { hanzi: '见', translation: 'encontrar' }, { hanzi: '聊天', translation: 'conversar' }, { hanzi: '吃饭', translation: 'comer' }, { hanzi: '工作', translation: 'trabalhar' },
  ] },
];

export const AULA5_HANZI_CORRECTIONS = [
  { hanzi: '房', title: 'Quarto / casa', detail: '户 fica compacto em cima e 方 se abre na parte inferior.' },
  { hanzi: '间', title: 'Cômodo / intervalo', detail: 'Escreva 门 por fora e 日 centralizado dentro da moldura.' },
  { hanzi: '外', title: 'Fora', detail: '夕 fica à esquerda; o ponto de 卜 permanece separado à direita.' },
  { hanzi: '只', title: 'Classificador de animais', detail: 'Aqui é 只, usado para animais pequenos; não confunda com 知.' },
  { hanzi: '猫', title: 'Gato', detail: '犭 fica estreito à esquerda e 苗 ocupa a maior parte do lado direito.' },
  { hanzi: '没', title: 'Não ter / não', detail: 'Comece pelos três pontos de água. Não confunda 没 com 梅.' },
  { hanzi: '见', title: 'Ver', detail: 'A parte superior fica compacta e 儿 se abre na base.' },
  { hanzi: '桌', title: 'Mesa', detail: 'Mantenha 日 no centro e 木 equilibrado na parte inferior.' },
  { hanzi: '在', title: 'Estar em', detail: 'Preserve a proporção entre a parte superior e 土, sem prolongar os traços além do necessário.' },
  { hanzi: '前', title: 'Frente', detail: '前 indica posição; não confunda com 钱, que significa dinheiro.' },
  { hanzi: '能', title: 'Poder / conseguir', detail: 'Organize o caractere em blocos compactos para não alargar a escrita.' },
  { hanzi: '到', title: 'Chegar', detail: '至 fica à esquerda e 刂 estreito à direita.' },
  { hanzi: '病', title: 'Doença / paciente', detail: '疒 envolve a parte interna; mantenha os dois pontos laterais visíveis.' },
  { hanzi: '医', title: 'Medicina', detail: '匚 envolve 矢 e é fechado pelo último traço horizontal.' },
  { hanzi: '作', title: 'Fazer / trabalhar', detail: '亻 fica estreito à esquerda e 乍 ocupa o lado direito.' },
];

export const AULA5_NUMBER_ROWS = [
  { hanzi: '下午两点', translation: 'duas da tarde' },
  { hanzi: '一点五十分', translation: 'uma e cinquenta' },
  { hanzi: '两点半', translation: 'duas e meia' },
  { hanzi: '一个房间', translation: 'um quarto — 个 é o classificador geral' },
  { hanzi: '一只小猫', translation: 'um gatinho — 只 classifica animais pequenos' },
  { hanzi: '一只小狗', translation: 'um cachorrinho' },
  { hanzi: '一名医生', translation: 'um médico — 名 classifica pessoas/profissões' },
  { hanzi: '两个房子', translation: 'duas casas' },
];

export const AULA5_PINYIN_NOTES = [
  { title: '哪里 — nǎli / 哪儿 — nǎr', detail: 'As duas formas perguntam “onde”. 哪 é 3º tom; não confunda 哪儿 com 那儿 (nàr), “ali”.' },
  { title: '上面 — shàngmian / 下面 — xiàmian', detail: 'Na fala corrente, 面 costuma ficar neutro nessas palavras de posição.' },
  { title: '左边 — zuǒbian / 右边 — yòubian', detail: '边 costuma ficar leve e neutro; preserve o 3º tom de 左 e a queda do 4º tom de 右.' },
  { title: '医院 — yīyuàn', detail: '医 é 1º tom e 院 é 4º: comece alto e termine com queda.' },
  { title: '医生 — yīshēng', detail: 'As duas sílabas são de 1º tom, altas e estáveis.' },
  { title: '漂亮 — piàoliang', detail: '亮 fica neutro nessa palavra; não faça uma queda forte na segunda sílaba.' },
  { title: '两点 — liáng diǎn', detail: 'Na fala natural, 两 sobe antes do 3º tom de 点.' },
  { title: '能 — néng / 到 — dào', detail: '能 é 2º tom crescente; 到 é 4º tom com queda firme.' },
  { title: '看见 — kànjiàn', detail: 'As duas sílabas têm 4º tom; faça duas quedas claras.' },
];

export const AULA5_WRITING_EXERCISES = [
  { id: 'a5-write-outside', prompt: 'Há um gatinho fora do quarto.', answer: '房间外有一只小猫。', hint: 'Comece pelo lugar, depois indique existência, quantidade e animal.' },
  { id: 'a5-write-under-table', prompt: 'O gatinho está debaixo da mesa.', answer: '小猫在桌子下面。', hint: 'Use o objeto de referência antes da posição.' },
  { id: 'a5-write-left-sofa', prompt: 'O gatinho está à esquerda do sofá.', answer: '小猫在沙发左边。', hint: 'A direção vem depois do móvel usado como referência.' },
  { id: 'a5-write-between', prompt: 'O cachorrinho está entre duas casas.', answer: '小狗在两个房子中间。', hint: 'Use um número, o classificador geral e a palavra “no meio”.' },
  { id: 'a5-write-no-see', prompt: 'Eu não vi.', answer: '我没看见。', hint: 'Negue o verbo de percepção com a forma adequada.' },
  { id: 'a5-write-meet-where', prompt: 'Onde vamos nos encontrar?', answer: '我们在哪儿见呢？', hint: 'Pergunte pelo lugar e termine de forma conversacional.' },
  { id: 'a5-write-can-arrive', prompt: 'Você consegue chegar às duas da tarde?', answer: '下午两点你能到吗？', hint: 'Coloque o horário antes da pessoa e use um modal antes de “chegar”.' },
  { id: 'a5-write-chat-subway', prompt: 'Eles estão conversando no metrô.', answer: '他们在地铁上聊天。', hint: 'Em chinês, coloque o lugar antes da ação.' },
  { id: 'a5-write-hospital', prompt: 'Eles estão consultando o médico no hospital.', answer: '他们在医院里看病。', hint: 'Lugar antes da ação relacionada a uma consulta.' },
  { id: 'a5-write-doctor', prompt: 'Você é médico?', answer: '你是一名医生吗？', hint: 'Use o classificador próprio para pessoa ou profissão.' },
  { id: 'a5-write-work-where', prompt: 'Onde seu irmão mais velho trabalha?', answer: '你哥哥在哪里工作？', hint: 'Pergunte o local da atividade profissional.' },
  { id: 'a5-write-meet-cinema', prompt: 'Vamos nos encontrar em frente ao cinema.', answer: '我们在电影院前见吧。', hint: 'Use o cinema como referência, a posição “em frente” e uma sugestão no fim.' },
];

export const AULA5_LISTENING_EXERCISES = [
  { phraseId: 'a5-outside-no-person', choices: ['Não há ninguém do lado de fora da porta.', 'Há alguém dentro do quarto.', 'A porta está aberta.'] },
  { phraseId: 'a5-cat-table-under', choices: ['O gatinho está debaixo da mesa.', 'O gatinho está sobre a mesa.', 'O cachorro está debaixo da cadeira.'] },
  { phraseId: 'a5-cat-sofa-left', choices: ['O gatinho está à esquerda do sofá.', 'O gatinho está à direita do sofá.', 'O gatinho está atrás do sofá.'] },
  { phraseId: 'a5-santa-behind', choices: ['O Papai Noel está atrás da cadeira.', 'O Papai Noel está diante da cadeira.', 'O Papai Noel está sobre a cadeira.'] },
  { phraseId: 'a5-dog-middle', choices: ['O cachorrinho está entre duas casas.', 'O cachorrinho está dentro da casa.', 'Há dois cachorros diante da casa.'] },
  { phraseId: 'a5-did-not-see', choices: ['Eu não vi.', 'Eu vi.', 'Eu não ouvi.'] },
  { phraseId: 'a5-meet-bookstore', choices: ['Vamos nos encontrar na livraria.', 'Vamos comprar livros.', 'Vamos nos encontrar na escola.'] },
  { phraseId: 'a5-can-arrive-two', choices: ['Você consegue chegar às duas da tarde?', 'Você chega às duas da manhã?', 'Você consegue sair às três?'] },
  { phraseId: 'a5-chat-subway', choices: ['Eles estão conversando no metrô.', 'Eles comem no metrô.', 'Eles esperam o metrô.'] },
  { phraseId: 'a5-eat-restaurant', choices: ['Eles estão comendo dentro do restaurante.', 'Eles trabalham no restaurante.', 'Eles conversam no hospital.'] },
  { phraseId: 'a5-treatment-hospital', choices: ['Eles estão consultando o médico no hospital.', 'Eles visitam a escola.', 'Eles trabalham no cinema.'] },
  { phraseId: 'a5-can-chinese', choices: ['Você consegue falar chinês?', 'Você gosta de estudar chinês?', 'Você ensina chinês?'] },
  { phraseId: 'a5-brother-work', choices: ['Onde seu irmão mais velho trabalha?', 'O que seu irmão estuda?', 'Seu irmão é médico?'] },
  { phraseId: 'a5-meet-cinema', choices: ['Vamos nos encontrar em frente ao cinema.', 'Vamos assistir ao filme dentro do cinema.', 'Vamos nos encontrar atrás da escola.'] },
];

export const AULA5_HOMEWORK = [
  'Leia em voz alta os diálogos da aula até conseguir manter o ritmo sem interromper a frase.',
  'Escolha objetos da sua casa e crie dez frases com 在 + objeto de referência + posição.',
  'Faça pares de frases com 有 e 没有 descrevendo o que existe em cada cômodo.',
  'Crie cinco frases com lugar antes da ação, usando 聊天、吃饭、看病、工作 e 学习.',
  'Monte um diálogo para combinar um encontro, mudando lugar e horário em cada repetição.',
  'Pratique cinco respostas com 能 e cinco com 不能 antes de um verbo.',
  'Escreva diariamente um pequeno parágrafo em chinês, entre 50 e 100 caracteres, usando apenas o vocabulário já estudado.',
  'Treine os caracteres 房、间、外、只、小、猫、没、见、桌、下、在、前、能、到、病、医、作 respeitando a ordem dos traços.',
];
