import type { LessonPhrase, LessonTopic, VocabularyGroup } from './aula1Data';

// Exemplos didáticos da aula de 05/10; sem conversas pessoais ou transcrição bruta.
// | indica blocos de treino, não pausas obrigatórias. Sandhi depende do ritmo da fala.
const rows = [
  ['see', '我能看到。', 'wǒ néng kàndào.', 'Eu consigo ver.'],
  ['new-cup-q', '这是你的新杯子吗？', 'zhè shì nǐ de xīn bēizi ma?', 'Este é o seu copo novo?'],
  ['new-cup', '是的，是我的新杯子。', 'shì de, | shì wǒ de xīn bēizi.', 'Sim, é o meu copo novo.'],
  ['cup-pretty', '这个杯子很漂亮。', 'zhè ge bēizi | hěn piàoliang.', 'Este copo é bonito.'],
  ['seller-q', '请问售货员在哪里？', 'qǐngwèn | shòuhuòyuán zài nálǐ?', 'Por favor, onde está o vendedor?'],
  ['seller', '他在那个柜台后面。', 'tā zài nà ge guìtái hòumian.', 'Ele está atrás daquele balcão.'],
  ['cup-here', '我的杯子在这边。', 'wǒ de bēizi zài zhèbian.', 'Meu copo está deste lado.'],
  ['sit-here', '我们坐这边吧。', 'wǒmen zuò zhèbian ba.', 'Vamos sentar aqui.'],
  ['sit-beside', '我坐在你旁边。', 'wǒ zuò zài nǐ pángbiān.', 'Eu sento ao seu lado.'],
  ['sit-window', '我坐在窗户旁边。', 'wǒ zuò zài chuānghu pángbiān.', 'Eu sento ao lado da janela.'],
  ['book-q', '请问书在哪里？', 'qǐngwèn | shū zài nálǐ?', 'Por favor, onde está o livro?'],
  ['book-here', '书在这边。', 'shū zài zhèbian.', 'O livro está deste lado.'],
  ['book-beside', '这本书在杯子旁边。', 'zhè běn shū | zài bēizi pángbiān.', 'Este livro está ao lado do copo.'],
  ['mom-money', '妈妈给我十元钱。', 'māma géi wǒ | shí yuán qián.', 'Minha mãe me dá dez yuans.'],
  ['total-q', '一共多少钱？', 'yígòng duōshao qián?', 'Quanto custa tudo?'],
  ['fifty', '五十块钱。', 'wǔshí kuài qián.', 'Cinquenta yuans.'],
  ['veg-price-q', '这些蔬菜多少钱？', 'zhèxiē shūcài duōshao qián?', 'Quanto custam estes legumes?'],
  ['veg-price', '这些蔬菜二十块钱。', 'zhèxiē shūcài | èrshí kuài qián.', 'Estes legumes custam vinte yuans.'],
  ['water-price', '这瓶水多少钱？', 'zhè píng shuǐ | duōshao qián?', 'Quanto custa esta garrafa de água?'],
  ['clothes-price-q', '这件衣服多少钱？', 'zhè jiàn yīfu | duōshao qián?', 'Quanto custa esta peça de roupa?'],
  ['cups-ten', '那些杯子十块钱一个。', 'nàxiē bēizi | shí kuài qián yí ge.', 'Aqueles copos custam dez yuans cada.'],
  ['cup-ten', '这个杯子十块钱。', 'zhè ge bēizi | shí kuài qián.', 'Este copo custa dez yuans.'],
  ['understood', '我明白了。', 'wǒ míngbai le.', 'Eu entendi.'],
  ['cup-price-q', '请问杯子多少钱一个？', 'qǐngwèn | bēizi duōshao qián yí ge?', 'Por favor, quanto custa cada copo?'],
  ['cups-five', '这些五块钱一个。', 'zhèxiē | wǔ kuài qián yí ge.', 'Estes custam cinco yuans cada.'],
  ['buy-this', '我买这个吧。', 'wó mǎi zhè ge ba.', 'Vou comprar este.'],
  ['book-price', '这本书六块零二分。', 'zhè běn shū | liù kuài líng èr fēn.', 'Este livro custa seis yuans e dois fen.'],
  ['supermarket-here', '这儿有一家超市。', 'zhèr yǒu yì jiā chāoshì.', 'Há um supermercado aqui.'],
  ['fruit-table', '桌子上有很多水果。', 'zhuōzi shang | yóu hěn duō shuíguǒ.', 'Há muitas frutas sobre a mesa.'],
  ['few-cars', '这儿的车很少。', 'zhèr de chē | hén shǎo.', 'Aqui há poucos carros.'],
  ['fruit-many', '这儿的水果真多。', 'zhèr de shuíguǒ | zhēn duō.', 'Aqui há mesmo muitas frutas.'],
  ['baozi-good', '这儿的包子真好吃。', 'zhèr de bāozi | zhēn hǎochī.', 'Os bolinhos daqui são muito gostosos.'],
  ['bought-fruit', '她买了三斤水果。', 'tā mǎi le | sān jīn shuíguǒ.', 'Ela comprou três jin de frutas.'],
  ['bought-apples', '我买了五斤苹果。', 'wó mǎi le | wǔ jīn píngguǒ.', 'Eu comprei cinco jin de maçãs.'],
  ['favorite-q', '你喜欢吃什么水果？', 'ní xǐhuan chī shénme shuíguǒ?', 'Que fruta você gosta de comer?'],
  ['like-mango', '我喜欢吃芒果。', 'wó xǐhuan chī mángguǒ.', 'Eu gosto de comer manga.'],
  ['mango-good', '芒果很好吃。', 'mángguǒ | hén hǎochī.', 'Manga é gostosa.'],
  ['love-mango', '我最爱吃芒果。', 'wǒ zuì ài chī mángguǒ.', 'Manga é a fruta que eu mais gosto de comer.'],
  ['jin-price-q', '这些水果多少钱一斤？', 'zhèxiē shuíguǒ | duōshao qián yì jīn?', 'Quanto custam estas frutas por jin?'],
  ['cheap-fruit', '超市的水果很便宜。', 'chāoshì de shuíguǒ | hěn piányi.', 'As frutas do supermercado são baratas.'],
  ['not-cheap-fruit', '超市的水果不便宜。', 'chāoshì de shuíguǒ | bù piányi.', 'As frutas do supermercado não são baratas.'],
  ['want-apples', '我想买两斤苹果。', 'wǒ | xiáng mǎi | liǎng jīn píngguǒ.', 'Eu quero comprar dois jin de maçãs.'],
  ['apples-cheap', '这儿的苹果真便宜。', 'zhèr de píngguǒ | zhēn piányi.', 'As maçãs daqui são muito baratas.'],
  ['fruit-not-few', '这儿的水果真不少。', 'zhèr de shuíguǒ | zhēn bù shǎo.', 'Aqui há mesmo bastante fruta.'],
  ['room-small', '我的房间不大。', 'wǒ de fángjiān | bú dà.', 'Meu quarto não é grande.'],
  ['cat-pretty', '那只小猫真好看。', 'nà zhī xiǎomāo | zhēn hǎokàn.', 'Aquele gatinho é muito bonito.'],
  ['classroom-big', '教室很大。', 'jiàoshì hěn dà.', 'A sala de aula é grande.'],
  ['apple-not-good', '这个苹果不好吃。', 'zhè ge píngguǒ | bù hǎochī.', 'Esta maçã não é gostosa.'],
  ['like-clothes', '我喜欢这件衣服。', 'wó xǐhuan | zhè jiàn yīfu.', 'Eu gosto desta peça de roupa.'],
  ['three-clothes', '三件衣服多少钱？', 'sān jiàn yīfu | duōshao qián?', 'Quanto custam três peças de roupa?'],
  ['clothes-three-hundred', '这件衣服三百元。', 'zhè jiàn yīfu | sān bǎi yuán.', 'Esta peça de roupa custa trezentos yuans.'],
  ['pen-price', '这支笔五元。', 'zhè zhī bǐ | wǔ yuán.', 'Esta caneta custa cinco yuans.'],
  ['clothes-opinion', '这件衣服怎么样？', 'zhè jiàn yīfu | zěnmeyàng?', 'O que você acha desta peça de roupa?'],
  ['computer-expensive', '这台电脑太贵了。', 'zhè tái diànnǎo | tài guì le.', 'Este computador é caro demais.'],
  ['learn-dress', '弟弟学习穿衣服。', 'dìdi xuéxí chuān yīfu.', 'Meu irmão mais novo aprende a se vestir.'],
  ['girl-pretty', '这个女孩很漂亮。', 'zhè ge nǚhái | hěn piàoliang.', 'Esta menina é bonita.'],
  ['two-boys', '我家有两个男孩。', 'wǒ jiā | yǒu liǎng ge nánhái.', 'Há dois meninos na minha família.'],
  ['store-there', '那儿有一家商店。', 'nàr yǒu yì jiā shāngdiàn.', 'Há uma loja ali.'],
  ['store-clothes', '这家商店衣服真多。', 'zhè jiā shāngdiàn | yīfu zhēn duō.', 'Esta loja tem muita roupa.'],
  ['clothes-not-expensive', '这件衣服不贵。', 'zhè jiàn yīfu | bú guì.', 'Esta peça de roupa não é cara.'],
  ['buy-one', '买一件吧。', 'mǎi yí jiàn ba.', 'Compre uma peça.'],
  ['girls-clothes', '这些是女孩子穿的衣服。', 'zhèxiē shì | nǚháizi chuān de yīfu.', 'Estas são roupas para meninas.'],
  ['boys-clothes', '男孩子的衣服在那儿。', 'nánháizi de yīfu | zài nàr.', 'As roupas de menino estão ali.'],
  ['restaurant-q', '这家饭店怎么样？', 'zhè jiā fàndiàn | zěnmeyàng?', 'O que você acha deste restaurante?'],
  ['restaurant-service', '这家饭店服务很好。', 'zhè jiā fàndiàn | fúwù hén hǎo.', 'O atendimento deste restaurante é bom.'],
  ['library-quiet', '这个图书馆很安静。', 'zhè ge túshūguǎn | hěn ānjìng.', 'Esta biblioteca é silenciosa.'],
  ['clothing-store', '这家服装店的衣服很好看。', 'zhè jiā fúzhuāngdiàn de yīfu | hén hǎokàn.', 'As roupas desta loja são bonitas.'],
  ['no-boys-clothes', '对不起，没有男孩子的衣服。', 'duìbuqǐ, | méiyǒu nánháizi de yīfu.', 'Desculpe, não temos roupas de menino.'],
] as const;
export const AULA7_KEY_PHRASES: LessonPhrase[] = rows.map(([id, hanzi, spokenPinyin, translation]) => ({ id: `a7-${id}`, hanzi, spokenPinyin, translation }));
const phrase = (id: string): LessonPhrase => {
  const found = AULA7_KEY_PHRASES.find(p => p.id === `a7-${id}`);
  if (!found) throw new Error(`Frase da aula 7 ausente: ${id}`);
  return found;
};
export const AULA7_LESSON_TOPICS: LessonTopic[] = [
  { marker: '边', title: 'Deste lado ou ao lado de algo?', summary: '这边 aponta um local; 旁边 usa uma referência.', points: ['这边 = deste lado/aqui; 那边 = daquele lado.', 'Pessoa ou objeto + 旁边: 你旁边、窗户旁边.', 'A posição vem depois da referência: 柜台后面.'], examples: [phrase('sit-here'), phrase('sit-beside'), phrase('book-beside'), phrase('seller')] },
  { marker: '些', title: 'Este, estes e aqueles', summary: '这个 indica um item; 这些 e 那些 indicam um conjunto.', points: ['这些 fica perto de quem fala; 那些 aponta um conjunto mais distante.', 'Depois de 些 não acrescente um classificador: 这些蔬菜.', '这儿的 + nome = aquilo que é daqui: 这儿的苹果.'], examples: [phrase('veg-price-q'), phrase('cups-ten'), phrase('apples-cheap')] },
  { marker: '钱', title: 'Perguntar preços e preço por unidade', summary: 'Objeto + 多少钱? pergunta quanto custa.', points: ['一共多少钱? pergunta o total.', '十块钱一个 = dez yuans cada; 多少钱一斤? pergunta preço por peso.', '元 e 块 equivalem quando falamos de dinheiro; 块 também pode significar pedaço em outro contexto.'], examples: [phrase('total-q'), phrase('cup-price-q'), phrase('cups-ten'), phrase('jin-price-q')] },
  { marker: '元', title: 'Yuan, jiao e fen', summary: '1 元 = 10 角 = 100 分. Na fala, 元 vira 块 e 角 vira 毛.', points: ['3,20 yuans: 三块二毛 ou 三块二.', '6,02 yuans: 六块零二分; o zero evita confundir com 6,20.', 'Os valores são exemplos de leitura, não preços atuais ou taxas de câmbio.'], examples: [phrase('book-price'), phrase('fifty')] },
  { marker: '斤', title: 'Comprar, vender e indicar peso', summary: '买 é comprar; 卖 é vender. 斤 é uma unidade de peso.', points: ['Na China continental, um jin equivale a 500 gramas; dois jin equivalem a um quilo.', 'Verbo + 了 + quantidade + objeto descreve aqui a compra realizada.', '斤 jīn não é 金, apesar da pronúncia igual.'], examples: [phrase('bought-fruit'), phrase('bought-apples'), phrase('want-apples')] },
  { marker: '真', title: 'Descrever sem inserir 是', summary: 'O adjetivo pode descrever diretamente o sujeito.', points: ['Use 很便宜、真好吃、太贵了, sem colocar 是 antes do adjetivo nesses modelos.', '很 nem sempre enfatiza “muito”; 真 destaca a avaliação.', '不少 significa bastante, não “muito pouco”. 不大 significa não grande, sem afirmar um tamanho exato.'], examples: [phrase('cheap-fruit'), phrase('fruit-not-few'), phrase('room-small'), phrase('computer-expensive')] },
  { marker: '不', title: 'Negação e pronúncia', summary: '不 nega o adjetivo; antes de um 4º tom, soa bú.', points: ['不贵 bú guì; 不大 bú dà.', '不便宜 bù piányi; 不好吃 bù hǎochī.', 'O pinyin de treino respeita os blocos da frase: não transforme mecanicamente todos os terceiros tons.'], examples: [phrase('clothes-not-expensive'), phrase('room-small'), phrase('not-cheap-fruit'), phrase('apple-not-good')] },
  { marker: '样', title: 'Pedir uma opinião', summary: '怎么样 pergunta como é algo ou o que a pessoa acha.', points: ['Pode perguntar qualidade, aparência, sabor ou atendimento, conforme o objeto.', 'Responda com uma avaliação: 很好、很好看、很好吃、很安静.', 'Não confunda 怎么样 com 多少钱: opinião e preço são perguntas diferentes.'], examples: [phrase('clothes-opinion'), phrase('restaurant-q'), phrase('restaurant-service'), phrase('library-quiet')] },
  { marker: '件', title: 'Roupas, aparelhos e pedaços', summary: 'Escolha o classificador conforme o objeto.', points: ['件 para roupas; 台 para aparelhos; 支 para canetas.', '块 para um pedaço; 片 para uma fatia. O formato importa.', '穿衣服 é vestir/usar roupa; 学习穿衣服 é aprender a se vestir.'], examples: [phrase('three-clothes'), phrase('computer-expensive'), phrase('pen-price'), phrase('learn-dress')] },
  { marker: '爱', title: 'Frutas e preferências', summary: '喜欢吃 expressa gostar de comer; 最爱吃 indica a preferência maior.', points: ['Troque a fruta e mantenha a estrutura da pergunta.', '爱吃 pode indicar adorar um alimento; 我爱你, dirigido a uma pessoa, é uma declaração afetiva mais forte.', 'O vocabulário de frutas e tipos de lojas é uma ampliação trabalhada na aula.'], examples: [phrase('favorite-q'), phrase('like-mango'), phrase('mango-good'), phrase('love-mango')] },
];
const words = (items: Array<[string, string]>): VocabularyGroup['words'] => items.map(([hanzi, translation]) => ({ hanzi, translation }));
export const AULA7_VOCABULARY_GROUPS: VocabularyGroup[] = [
  { title: 'Copos, objetos e pessoas da loja', description: 'Quem atende, onde paga e o que você procura.', words: words([['杯子','copo'],['被子','cobertor'],['水杯','copo de água'],['纸杯','copo de papel'],['保温杯','copo térmico'],['茶杯','xícara de chá'],['玻璃杯','copo de vidro'],['售货员','vendedor'],['收银员','operador de caixa'],['收银台','balcão do caixa'],['服务员','atendente'],['顾客','cliente'],['柜台','balcão']]) },
  { title: 'Localização e conjuntos', description: 'Perto, longe e ao lado de uma referência.', words: words([['这边','deste lado'],['那边','daquele lado'],['旁边','ao lado'],['这儿','aqui'],['那儿','ali'],['这些','estes'],['那些','aqueles'],['哪些','quais'],['窗户','janela'],['后面','atrás']]) },
  { title: 'Compras, preços e medidas', description: 'Dinheiro, avaliação e quantidade.', words: words([['钱','dinheiro'],['人民币','moeda chinesa'],['美元','dólar americano'],['英镑','libra esterlina'],['元','yuan'],['块','yuan ou pedaço'],['角','décimo de yuan'],['毛','jiao na fala'],['分','centésimo de yuan'],['斤','jin: 500 gramas'],['买','comprar'],['卖','vender'],['一共','ao todo'],['便宜','barato'],['贵','caro'],['打折','dar desconto'],['价格','preço'],['怎么样','o que acha'],['件','classificador de roupas'],['台','classificador de aparelhos'],['片','fatia'],['穿','vestir']]) },
  { title: 'Frutas e alimentos', description: 'Frutas ampliadas pela professora e itens usados nas compras.', words: words([['水果','fruta'],['苹果','maçã'],['蓝莓','mirtilo'],['香蕉','banana'],['西瓜','melancia'],['橙子','laranja'],['葡萄','uva'],['芒果','manga'],['梨','pera'],['菠萝','abacaxi'],['桃子','pêssego'],['蔬菜','legumes'],['面包','pão'],['蛋糕','bolo'],['包子','bolinho'],['咖啡','café']]) },
  { title: 'Tipos de lojas', description: 'Ampliação: pratique o que cada estabelecimento vende.', words: words([['商店','loja'],['商场','shopping'],['超市','supermercado'],['水果店','loja de frutas'],['蔬菜店','loja de legumes'],['面包店','padaria'],['便利店','loja de conveniência'],['文具店','papelaria'],['鞋店','loja de sapatos'],['服装店','loja de roupas'],['药店','farmácia'],['奶茶店','loja de chá com leite'],['咖啡店','cafeteria'],['手机店','loja de celulares'],['书店','livraria']]) },
  { title: 'Roupas e avaliações', description: 'Descrever aparência, sabor e ambiente.', words: words([['衣服','roupa'],['男孩','menino'],['女孩','menina'],['漂亮','bonito'],['好看','bonito de ver'],['好吃','gostoso'],['可爱','fofo'],['安静','silencioso'],['真','realmente'],['很','advérbio de grau'],['少','pouco'],['多','muito'],['最爱','gostar mais'],['明白','entender']]) },
];
export const AULA7_NUMBER_ROWS = [
  { hanzi: '一元 / 一块', translation: '1 yuan: unidade formal / forma coloquial' },
  { hanzi: '一角 / 一毛', translation: '0,10 yuan: um jiao / um mao' },
  { hanzi: '二分', translation: '0,02 yuan: dois fen' },
  { hanzi: '二毛', translation: '0,20 yuan: dois mao' },
  { hanzi: '三块二毛 / 三块二', translation: '3,20 yuans' },
  { hanzi: '六块零二分', translation: '6,02 yuans' },
  { hanzi: '七块二毛', translation: '7,20 yuans' },
  { hanzi: '十块钱一个', translation: '10 yuans cada' },
  { hanzi: '两斤', translation: '1 kg na China continental' },
  { hanzi: '三百元', translation: '300 yuans' },
];
export const AULA7_PINYIN_NOTES = [
  { title: '杯子 / 被子 — bēizi / bèizi', detail: 'O primeiro tom é alto e estável; o quarto desce. 子 é neutro nessas duas palavras.' },
  { title: '买 / 卖 — mǎi / mài', detail: 'Comprar tem terceiro tom; vender tem quarto. Não confunda o sentido ou o caractere.' },
  { title: '便宜 — piányi', detail: 'Na palavra que significa barato, 便 se lê pián e 宜 fica neutro. Não leia biàn yí.' },
  { title: '不贵 / 不大 — bú guì / bú dà', detail: '不 muda de quarto para segundo antes de um quarto tom. Em 不便宜 e 不好吃 conserva bù.' },
  { title: '一共 / 一件 / 一斤', detail: 'Antes de quarto tom: yígòng, yí jiàn. Antes de primeiro tom: yì jīn. Em números isolados, 一 pode conservar yī.' },
  { title: '哪里 — nǎlǐ → nálǐ', detail: 'A professora treinou a leitura plena de dois terceiros tons, que soa 2–3. A variante nǎli, com 里 neutro, também ocorre; não é um erro.' },
  { title: '水果 / 很好吃 — shuíguǒ / hén hǎochī', detail: 'Nestes blocos de dois terceiros tons, o primeiro muda para segundo. O pinyin de treino marca essa mudança.' },
  { title: '我想买两斤 — blocos de fala', detail: 'Uma leitura de treino é 我 | 想买 | 两斤: wǒ | xiáng mǎi | liǎng jīn. Os agrupamentos podem variar com a fala; não altere todos os terceiros tons em cadeia.' },
  { title: '员 / 元 — yuán', detail: 'Mesma pronúncia, segundo tom: 员 em profissões; 元 em dinheiro. 收银台 termina em tái, segundo tom.' },
  { title: '怎么样 / 明白', detail: 'Treine zěnmeyàng e míngbai: 么 e 白 ficam leves nessas palavras. 这儿 e 那儿 têm final r ligado à sílaba.' },
];
export const AULA7_HANZI_CORRECTIONS = [
  { hanzi: '买 / 卖', title: 'Comprar e vender', detail: '卖 tem 十 no topo. Mais traços não significa comprar mais: o significado é vender.' },
  { hanzi: '杯 / 被', title: 'Copo e cobertor', detail: '杯 tem 木 à esquerda; 被 tem o radical de roupa 衤. Observe também a diferença de tom.' },
  { hanzi: '斤 / 金', title: 'Peso, não ouro', detail: 'A transcrição troca 斤 por 金. Para a unidade de peso das frutas, escreva 斤.' },
  { hanzi: '块 / 快', title: 'Yuan/pedaço, não rápido', detail: '块 começa com 土; 快 começa com 忄. Preços e pedaços usam 块.' },
  { hanzi: '员 / 元', title: 'Pessoa ou unidade monetária', detail: '售货员、收银员 e 服务员 usam 员. 十元钱 usa 元. As trocas por 原 na transcrição não pertencem a esses exemplos.' },
  { hanzi: '那 / 哪', title: 'Aqueles ou quais', detail: '那些 = aqueles. 哪些 = quais. 哪 acrescenta 口 à esquerda.' },
  { hanzi: '件', title: 'Uma peça de roupa', detail: 'Use 件 em 一件衣服; não 剑 (espada), que aparece por erro de reconhecimento na transcrição.' },
  { hanzi: '商店 / 穿 / 钱', title: 'Escrita reforçada na aula', detail: 'Treine cada palavra em três etapas: leitura, significado e uso numa frase. Copie os caracteres com atenção antes de escrever sem modelo.' },
];
const writing = [
  ['seller-q','Pergunte por uma pessoa com cortesia.'], ['sit-here','Faça uma sugestão sem precisar de objeto de referência.'],
  ['sit-beside','Use a pessoa como referência da posição.'], ['book-beside','O livro é o sujeito; o copo é a referência.'],
  ['total-q','Pergunte pelo total, não por uma unidade.'], ['veg-price-q','Use o demonstrativo de conjunto próximo.'],
  ['water-price','Escolha o classificador de garrafas.'], ['clothes-price-q','Escolha o classificador de roupas.'],
  ['cups-ten','Deixe o preço por unidade depois do objeto.'], ['bought-fruit','Marque a compra realizada e indique o peso.'],
  ['bought-apples','Não confunda comprar com vender.'], ['want-apples','Expresse desejo de comprar antes do peso.'],
  ['apples-cheap','Descreva as maçãs daqui sem inserir o verbo ser.'], ['fruit-not-few','Use a expressão negativa que significa bastante.'],
  ['room-small','Negue a qualidade sem indicar um tamanho exato.'], ['clothes-not-expensive','Negue o preço alto diretamente.'],
  ['clothes-opinion','Pergunte opinião, não preço.'], ['computer-expensive','Use o classificador de aparelhos e a ideia de excesso.'],
  ['learn-dress','Depois de aprender, diga a habilidade praticada.'], ['restaurant-service','Avalie o atendimento do estabelecimento.'],
  ['library-quiet','Descreva o ambiente sem inserir o verbo ser.'], ['boys-clothes','As roupas são o sujeito; o lugar vem depois.'],
] as const;
export const AULA7_WRITING_EXERCISES = writing.map(([id,hint]) => ({ id: `a7-w-${id}`, prompt: phrase(id).translation, answer: phrase(id).hanzi, hint }));
const listening = [
  ['seller-q','Onde fica o caixa?','Quanto custa o balcão?'], ['seller','Ele está na frente daquele balcão.','Ele está ao lado da janela.'],
  ['sit-here','Vamos sentar ao lado dela.','Vamos comprar aqui.'], ['book-beside','Este copo está ao lado do livro.','Este livro está debaixo do copo.'],
  ['total-q','Quanto custa cada um?','Quantos itens há?'], ['veg-price-q','Quanto custam aquelas frutas?','Quanto pesam estes legumes?'],
  ['cups-ten','Aqueles copos custam cinco yuans cada.','Aqueles copos custam dez yuans no total.'], ['book-price','Este livro custa seis yuans e dois jiao.','Este livro custa sessenta e dois yuans.'],
  ['bought-fruit','Ela vendeu três jin de frutas.','Ela comprou cinco jin de frutas.'], ['want-apples','Eu quero vender dois jin de maçãs.','Eu comprei dois jin de maçãs.'],
  ['like-mango','Eu gosto de comer maçã.','Eu quero vender manga.'], ['cheap-fruit','As frutas do supermercado não são baratas.','Os legumes do supermercado são caros.'],
  ['fruit-not-few','Aqui há muito pouca fruta.','Aqui não há frutas.'], ['clothes-not-expensive','Esta peça de roupa é cara.','Esta peça de roupa não é bonita.'],
  ['computer-expensive','Este computador é barato demais.','Esta televisão é cara demais.'], ['clothes-opinion','Quanto custa esta peça de roupa?','De quem é esta peça de roupa?'],
  ['clothes-three-hundred','Esta peça de roupa custa trinta yuans.','Estas três peças de roupa custam cem yuans.'], ['boys-clothes','As roupas de menina estão aqui.','Os meninos estão naquela loja.'],
  ['restaurant-service','A comida deste restaurante é boa.','O atendimento deste restaurante não é bom.'], ['library-quiet','Esta biblioteca é grande.','Esta livraria é silenciosa.'],
] as const;
export const AULA7_LISTENING_EXERCISES = listening.map(([id,...others]) => ({ phraseId: `a7-${id}`, choices: [phrase(id).translation,...others] }));
export const AULA7_HOMEWORK = [
  'Orientação da professora: pratique perguntas de preço com copos, frutas, legumes, roupas e celulares; responda com valores diferentes.',
  'Pratique preço por unidade e por jin. Compare cinco yuans cada com dez yuans cada, sem confundir total e unidade.',
  'Use uma fruta de sua preferência para formar frases de gosto, localização, compra, peso e preço.',
  'Separe os adjetivos que você já conhece e construa frases com 很, 真 e 不. Não coloque 是 automaticamente.',
  'Revise as palavras difíceis pela pronúncia, hanzi, significado, uso, escrita e diálogo — não só pelo pinyin.',
  'Escreva 售货员、这边、钱、块、那、斤、便宜、商店、件、怎么样、贵 e 穿; leia uma frase com cada uma.',
  'Continue o livro, o caderno de exercícios e os deveres enviados pela professora; o site é um apoio, não substitui esses materiais.',
  'Os exercícios interativos foram preparados pelo site com base na aula. As capturas de dever mencionadas no PDF não estão anexadas à transcrição.',
];
